server:
  name: sanic_backend
  http:
    port: 80

  component:
    controller: "backend.controller"
    service: "backend.service"
    repository: "backend.repository"
    datasource: "backend.core.datasource"

  log:
    console: true
    save_path: logs
    console_level: DEBUG
    stdout_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    filehandle_level: [ "INFO", "ERROR" ]
    filehandle_format: "[%(levelname)s] %(asctime)s [%(pathname)s:%(lineno)d] %(funcName)s: %(message)s"
    backup_count: 10
    max_million_bytes: 100


datasource:
    mysql:
        db_name: sanic_backend_system
        host: 222.197.219.18
        user: root
        password: szq1026
        port: 13306
        max_usage: 1000
