server:
  name: sanic_backend
  http:
    port: 80

  component:
    controller: "backend.controller"
    service: "backend.service"
    repository: "backend.repository"
    datasource: "backend.core.datasource"

  log:
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> |<yellow>[{process.name}:{process}]</yellow> <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    retention: "10 days"
    save_path: "./logs/sanic_boot_{time}.log"
    level: "DEBUG"



datasource:
    mysql:
        db_name: sanic_backend_system
        host: xxx
        user: root
        password: xxx
        port: xxx
        max_usage: 1000
